//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class parentsstudentov
    {
        public string lastname { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public Nullable<int> id_studenta { get; set; }
        public string adress { get; set; }
        public int id_parents { get; set; }
    
        public virtual students students { get; set; }
    }
}
