//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int id_sotrudnika { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middlename { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Pasport_data { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> Date_in { get; set; }
        public Nullable<int> id_otdel { get; set; }
        public Nullable<int> id_statusa_obrazovanie { get; set; }
        public Nullable<int> id_deti { get; set; }
        public Nullable<int> id_doljnost { get; set; }
    }
}
