//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public students()
        {
            this.parentsstudentov = new HashSet<parentsstudentov>();
        }
    
        public string lastname { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public Nullable<System.DateTime> date_birthday { get; set; }
        public Nullable<int> pasport { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string gender { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<System.DateTime> enrollment { get; set; }
        public Nullable<System.DateTime> dropout { get; set; }
        public int id_studenta { get; set; }
    
        public virtual group group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parentsstudentov> parentsstudentov { get; set; }
    }
}
