//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class База_данных_трудовых_книг
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public База_данных_трудовых_книг()
        {
            this.Упрвляющий_баз_данных = new HashSet<Упрвляющий_баз_данных>();
        }
    
        public int id_база_данных_трудовых_книг { get; set; }
        public Nullable<int> количество_книжек { get; set; }
        public Nullable<System.DateTime> дата_поступления_книжки { get; set; }
        public Nullable<System.DateTime> дата_выдачи_книги { get; set; }
        public Nullable<int> id_трудовая_книга { get; set; }
    
        public virtual Трудовая_книжка Трудовая_книжка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Упрвляющий_баз_данных> Упрвляющий_баз_данных { get; set; }
    }
}
