//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Владелец_трудовой_книги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Владелец_трудовой_книги()
        {
            this.Трудовая_книжка = new HashSet<Трудовая_книжка>();
        }
    
        public int id_владелец_трудовой_книги { get; set; }
        public string имя { get; set; }
        public string фамилия { get; set; }
        public string номер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Трудовая_книжка> Трудовая_книжка { get; set; }
    }
}
