//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные
    {
        public int id_клиент { get; set; }
        public Nullable<int> серия { get; set; }
        public Nullable<int> номер { get; set; }
        public string кем_выдан { get; set; }
        public string адресс { get; set; }
    
        public virtual Клиент Клиент { get; set; }
    }
}
