//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int id_заказ { get; set; }
        public Nullable<int> номер_заказа { get; set; }
        public Nullable<decimal> цена { get; set; }
        public Nullable<System.DateTime> дата_заказа { get; set; }
        public Nullable<int> id_склад { get; set; }
        public Nullable<int> id_завод { get; set; }
        public Nullable<int> id_магазин { get; set; }
    
        public virtual Завод Завод { get; set; }
        public virtual Магазин Магазин { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
