//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ__20_09_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ__20_09_()
        {
            this.Полиграфия__20_09_ = new HashSet<Полиграфия__20_09_>();
        }
    
        public int id_заказа { get; set; }
        public string Название { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public int id_клиента { get; set; }
    
        public virtual Клиент__20_09_ Клиент__20_09_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Полиграфия__20_09_> Полиграфия__20_09_ { get; set; }
    }
}
