//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент__20_09_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Клиент__20_09_()
        {
            this.Заказ__20_09_ = new HashSet<Заказ__20_09_>();
            this.Фирма__20_09_ = new HashSet<Фирма__20_09_>();
        }
    
        public int id_клиента { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> Номер_телефона { get; set; }
        public string Почта_клиента { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ__20_09_> Заказ__20_09_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Фирма__20_09_> Фирма__20_09_ { get; set; }
    }
}
