//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сейф
    {
        public int id_сейф { get; set; }
        public Nullable<int> номер { get; set; }
        public Nullable<int> id_трудовая_книжка { get; set; }
    
        public virtual Трудовая_книжка Трудовая_книжка { get; set; }
    }
}
