//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int Код_студента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Пол { get; set; }
        public string Улица { get; set; }
        public Nullable<int> Дом { get; set; }
        public Nullable<int> Квартира { get; set; }
        public string Группа_здоровья { get; set; }
        public string Увлечения { get; set; }
        public Nullable<int> Курс { get; set; }
        public string Телефон { get; set; }
    }
}
