//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страховка
    {
        public int id_страховка { get; set; }
        public Nullable<int> id_клиент { get; set; }
        public Nullable<int> id_сотрудник { get; set; }
        public Nullable<decimal> стоимость_страховки { get; set; }
        public Nullable<int> серия_номер_страховки { get; set; }
        public Nullable<int> первоначальный_взнос { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Срок_заключения_страховки Срок_заключения_страховки { get; set; }
        public virtual Тип_страховки Тип_страховки { get; set; }
    }
}
