//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тип_страховки
    {
        public int id_страховка { get; set; }
        public string вид_страховки { get; set; }
    
        public virtual Страховка Страховка { get; set; }
    }
}
