//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Участок
    {
        public int id_участок { get; set; }
        public Nullable<int> id_врач { get; set; }
        public string название_участка { get; set; }
        public string адрес_участка { get; set; }
        public Nullable<int> число_жителей { get; set; }
    
        public virtual Врач Врач { get; set; }
    }
}
