//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фирма__20_09_
    {
        public int id_фирмы { get; set; }
        public string Название { get; set; }
        public string Почта_фирмы { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> id_сотрудника { get; set; }
        public Nullable<int> id_клиента { get; set; }
    
        public virtual Клиент__20_09_ Клиент__20_09_ { get; set; }
        public virtual Сотрудник__20_09_ Сотрудник__20_09_ { get; set; }
    }
}
